---

name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup env
        run: npm install

      - name: Build Page
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |-
          export PATH="$PWD/node_modules/.bin"
          ./ci/release.ts
