---

name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1

      - name: Debug
        run: |-
          for file in node_modules/.bin/**
          do
            echo "$file"
          done

      - name: Build Page
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: npm run ci
